[package]
name = "xsvutils"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "xsvutils-rs"
path = "../src/main.rs"

[dependencies]
regex = "1"
lazy_static = "1"
memchr = "2"
url = "1"
structopt = "0.2"

[profile.release]
lto = true
